name: Release

on:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml

  package:
    uses: ./.github/workflows/package.yml

  release:
    needs: [test, package]
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    uses: macieklamberski/kvalita/.github/workflows/shared-release.yml@main
    with:
      build: true
    secrets: inherit
